app:
  timezone: America/Mexico_City
  paths:
    session: src/resources/session.json
    resources: src/resources
    cache: src/cache
qx:
  host: qxbroker.com
  urls:
    base: https://qxbroker.com/en/
    login: sign-in
    logged: trade
    logout: logout
  wss:
    url: wss://ws2.qxbroker.com/socket.io/?EIO=3&transport=websocket
    origin: https://qxbroker.com
    host: ws2.qxbroker.com
    enable_trace: false
    ping:
      interval: 25
      timeout: 15
      payload: 2
    retry:
      on: true 
      max_attempts: 5 
      wait: 5
    msg_interval:
      secs: 20
  proxies: None
  emails:
    no_reply: noreply@qxbroker.com
  account:
    user: your@email.com
    pass: your_pass
  locators:
    user: Email
    pass: Password
    submit_login: Sign In
    pin_sent: Please enter the PIN-code we've just sent to your email
    pin: Enter 6-digit code...
    submit_pin: Sign in
imap:
  server: mail.spacemail.com
  email: your@email.com
  pass: your_pass
  port: 993
browser:
  user_data_dir: browser/instance/quotex.default