base_url: qxbroker.com
host: qxbroker.com
imap_server: mail.spacemail.com
imap_email: admin@appniverse.com
imap_pass: 1Ac43E47-CAD0-4D8d-aeC4-8b69F991e444
imap_port: 993
proxies: None
qx_no_reply_email: noreply@qxbroker.com
qx_email: emma_fiver@appniverse.com
qx_pass: fiver_emmA123.
resource_path: .
timezone: America/Mexico_City
user_data_dir: browser/instance/quotex.default
asset: AUDNZD_otc