base_url: qxbroker.com
host: qxbroker.com
imap_server: mail.spacemail.com
imap_email: your_email
imap_pass: your_pass
imap_port: 993
proxies: None
qx_no_reply_email: noreply@qxbroker.com
qx_email: your_email
qx_pass: your_pass
resource_path: .
timezone: America/Mexico_City
user_data_dir: browser/instance/quotex.default
asset: AUDNZD_otc