base_url: qxbroker.com
host: qxbroker.com
imap_server: your_imap_server.com
imap_email: your_email@domain.com
imap_pass: your_password
imap_port: 993
proxies: None
qx_no_reply_email: noreply@qxbroker.com
qx_email: your_email@domain.com
qx_pass: your_password
resource_path: .
timezone: America/Mexico_City
user_data_dir: browser/instance/quotex.default
