base_url: qxbroker.com
email: your@email.com
email_pass: your_password_goes_here
host: qxbroker.com
imap_port: 993
imap_server: your_imap_server
password: account_password_here
proxies: None
quotex_email: noreply@qxbroker.com
resource_path: .
user_data_dir: browser/instance/quotex.default
timezone: America/Mexico_City
